<header id="BackstageHeader">
    <div id="headerbox">
        <div id="logobox">
            <img src="../images/logo/LOGO_white.png" alt="">
        </div>
        <div id="inforbox">
            <div id="avatorbox">
                <img id="avator" src="" alt="">
            </div>
            <div id="admininfor">
                <div id="admin_no"></div><br>
                <div id="admin_id"></div>
            </div>
            <button id="btnLogout" class="btnB_L_yellow"><p>登出</p><div class="bg"></div></button>
        </div>
    </div>
</header>