<?php 
    session_start();
    unset($_SESSION['mem_no']);
    unset($_SESSION['mem_id']);
    unset($_SESSION['mem_name']);
    unset($_SESSION['mem_acc']);
    unset($_SESSION['mem_psw']);
    unset($_SESSION['mem_mail']);
    unset($_SESSION['mem_build']);
    unset($_SESSION['mem_point']);
    unset($_SESSION['mem_avator']);
    unset($_SESSION['mem_bg']);
    unset($_SESSION['class']);
    unset($_SESSION['mem_badge1']);
    unset($_SESSION['mem_badge2']);
    unset($_SESSION['mem_badge3']);
    unset($_SESSION["guide_no"]);
?>